// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqEhL9nM8R7-b3XJqEhL9nM8R7-b3XJqE',
    appId: '1:563584335869:web:wassit-app',
    messagingSenderId: '563584335869',
    projectId: 'wassit-app-dca48',
    authDomain: 'wassit-app-dca48.firebaseapp.com',
    storageBucket: 'wassit-app-dca48.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqEhL9nM8R7-b3XJqEhL9nM8R7-b3XJqE',
    appId: '1:563584335869:android:wassit-app',
    messagingSenderId: '563584335869',
    projectId: 'wassit-app-dca48',
    storageBucket: 'wassit-app-dca48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqEhL9nM8R7-b3XJqEhL9nM8R7-b3XJqE',
    appId: '1:563584335869:ios:wassit-app',
    messagingSenderId: '563584335869',
    projectId: 'wassit-app-dca48',
    storageBucket: 'wassit-app-dca48.appspot.com',
    iosBundleId: 'com.wassit.wassitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqEhL9nM8R7-b3XJqEhL9nM8R7-b3XJqE',
    appId: '1:563584335869:macos:wassit-app',
    messagingSenderId: '563584335869',
    projectId: 'wassit-app-dca48',
    storageBucket: 'wassit-app-dca48.appspot.com',
    iosBundleId: 'com.wassit.wassitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqEhL9nM8R7-b3XJqEhL9nM8R7-b3XJqE',
    appId: '1:563584335869:windows:wassit-app',
    messagingSenderId: '563584335869',
    projectId: 'wassit-app-dca48',
    authDomain: 'wassit-app-dca48.firebaseapp.com',
    storageBucket: 'wassit-app-dca48.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );
} 